### ISSUE TITLE
CSSクラスの再共有です

### ISSUE THREAD

**Issue by y-takahasi** [internousdevwork/yellow#2]
ふみ:   ページタイトル→**pageTitle** 検索結果なし→**notFoundMsg**
　　　    東:   入力テーブル→**imputTable**
りょうせい:    商品詳細上→**productDetails**関連商品→**relatedProductListBox**
　    たつや:    商品リスト→**productList**
　    かずま:    カテゴリ検索→**categorySelect**検索ワード→**searchWordInput**
ゆうたろう:     ボタン→**button**
   こなみん:     サイトタイトル→**siteTitle**　エラーメッセージ→**errorMsgBox**
    まっすー:    カート合計金額→**totalPrice** 完了メッセージ→**completeMsgBox**

**Comment by KazumaSakai** [comment]
notFoundMsg -> **notFoundMsgBox**

**Comment by KazumaSakai** [comment]
クラス名は
```
.vertical-list-table
{
	width: 90%;
	border-collapse: separate;
	border-spacing: 0;
}
```
などを
```
.指定したクラス名
{
	width: 90%;
	border-collapse: separate;
	border-spacing: 0;
}
```
の用に変更してください  

確認チェックリスト
- [ ] notFoundMsg
- [ ] imputTable
- [ ] productDetails
- [ ] relatedProductListBox
- [ ] productList
- [ ] categorySelect
- [ ] searchWordInput
- [ ] button
- [ ] siteTitle
- [ ] errorMsgBox
- [ ] totalPrice
- [ ] completeMsgBox
