### ISSUE TITLE
２月１５日担当編成

### ISSUE THREAD

**Issue by y-takahasi** [internousdevwork/yellow#20]
機能実装はレビューが通りました。
○担当割
りょうせい、たつや→CSS画面実装変更
こなみん→ユーザー登録
まっすー→ログイン・ログアウト　カート
ふみ→検索
東→商品一覧
侑→マイページ機能

○確認終了後にしか確認できない箇所
ユーザー登録後→ログイン再設定
カート機能終了後→宛先選択、決済完了機能後→商品購入履歴
宛先情報選択後→宛先情報登録

○シナリオ試験チェックがつかない部分はコメントに書いてください。
EX　ヘッダー　p.4 1-1 　ログインボタンが押せない

当日の終わったところまでの進捗を最後に記入してください。
・EX　カート　　ｐ.41 1-5まで

**Comment by y-takahasi** [comment]
マイページ確認終了エラーなし

**Comment by y-takahasi** [comment]
> 機能実装はレビューが通りました。
> ○担当割
> りょうせい、たつや→CSS画面実装変更
> こなみん→ユーザー登録
> まっすー→ログイン・ログアウト　カート
> ふみ→検索
> 東→商品一覧
> 侑→マイページ機能
> 
> ○確認終了後にしか確認できない箇所
> ユーザー登録後→ログイン再設定
> カート機能終了後→宛先選択、決済完了機能後→商品購入履歴
> 宛先情報選択後→宛先情報登録
> 
> ○シナリオ試験チェックがつかない部分はコメントに書いてください。
> EX　ヘッダー　p.4 1-1 　ログインボタンが押せない
> 
> 当日の終わったところまでの進捗を最後に記入してください。
> ・EX　カート　　ｐ.41 1-5まで

**Comment by hijiri0423** [comment]
ふみ　検索　終了

**Comment by anzu12912** [comment]
東将太　商品一覧／商品詳細機能　終了

**Comment by kahomasuyama** [comment]
増山　ログイン ・ログアウト　カート　終了

**Comment by konami-ueno** [comment]
上野　ユーザー登録　終了

**Comment by konami-ueno** [comment]
上野　ヘッダー　終了

**Comment by hijiri0423** [comment]
佐々木　パスワード再設定
P37-2 　パスワード再設定画面で以下のエラーメッセージが"含まれていること"
「新しいパスワードと新しいパスワード(再確認)が一致しません。」が含まれていない。

**Comment by hijiri0423** [comment]
> 佐々木　パスワード再設定
> P37-2 　パスワード再設定画面で以下のエラーメッセージが"含まれていること"
> 「新しいパスワードと新しいパスワード(再確認)が一致しません。」が含まれていない。

ユーザー登録後
再度入力し問題ないことを確認。　終了

**Comment by y-takahasi** [comment]
商品購入履歴,宛先情報登録完了

**Comment by y-takahasi** [comment]
CSS完了
画像実装レビュー待ち
