### ISSUE TITLE
二行以上の改行があるファイル

### ISSUE THREAD

**Issue by KazumaSakai** [internousdevwork/yellow#5]
二行連続で改行するのは一行だけの改行に修正しましょう。
現在二行以上改行しているのは以下のファイルです。
- [x] settlementComplete.jsp
- [x] AddCartAction.java
- [x] UserInfoDAO.java
- [x] CartInfoDTO.java

**Comment by konami-ueno** [comment]
[fix]UserInfoDAO 改行修正#5
